### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by vtolstov** [gholt/ring#36]
Does this project maintained and why after so much time it in not production ready?

Also i want to use it for my toy storage system:
Volume - disk attached to vm
Volume represented as fixed sized blocks (4M) ech block have own id.
Physical server have 3 disks , each block have replication count 2. So it placed on two of three disks on current server. Also i have not one server but may (3 for example) Also i want to have each block not only current physical server, but also on nearest. Does it possible to do that using replica count and tiering?
Also if i want to use utp for communication how hard to do that ?

**Comment by gholt** [comment]
Hi! Thanks for your interest in this package.

The package has been under somewhat off and on development for quite some time, yes. Changing priorities at work have been the main reason. It started off as a research project, then included in a developing project, then we just got bought by another company and development is starting up again. Anyway, hopefully that explains a little of the status here.

This package does the opposite of nearest, so it probably won't fit your use case. This package deliberately places replicas as far apart as possible for durability and availability reasons. The idea is that the lowest tier would represent disks on a server, the next tier servers in a rack or behind a switch, the next tier being a datacenter room, the next a datacenter, geographical region, etc. The replica placement would try its best to place them as far apart as possible, such as in different datacenters, and failing that, in separate server groups, etc.

As far as UDP communication, that would require completely new work on your part. Other than the TCPMsgRing, this library really provides no communication measures. In fact, the TCPMsgRing is likely to get moved to its own package at some point since it honestly doesn't make much sense to be in this package.
This package is meant to be a data structure package, and how that structure is made use of should be outside its scope.

Anyway, hopefully this clears some things up. You are certainly free to take any ideas from this work and make them your own: reversing the furthest vs. nearest concepts, for example.

**Comment by vtolstov** [comment]
Big Thanks!
